### PR TITLE
WIP: Add early demo for OORB

### PR DESCRIPTION
**Pull request by HoodedCrow**
This should be working on dev now.
I am not planning to merge this (should I?), but you can you it for testing.

### CODE REVIEW

**Comment by HoodedCrow** [comment]
You'll also need https://github.com/B612-Asteroid-Institute/adam_home/pull/70, which is not yet merged due to failing Travis.

**Comment by HoodedCrow** [comment]
You'll also need https://github.com/B612-Asteroid-Institute/adam_home/pull/70, which is not yet merged due to failing Travis.

**Comment by carise** [comment]
@AstrogatorJohn how's this PR coming along? should it be merged?

**Comment by AstrogatorJohn** [comment]
@Carise: I haven't checked this out. Are we still running OORB?

**Comment by carise** [comment]
We don't plan on using oorb any time soon, so I will close this PR.

**Pull request closed without merging**
